load("//javascript/angular2:build_defs.bzl", "ng_module")

package(default_visibility = ["//experimental/users/jasonlewis/scaffolding/angular/example-routing-basic:internal"])

ng_module(
    name = "routes",
    srcs = ["routes.ts"],
    deps = [
        "//third_party/javascript/angular2:core",
        "//third_party/javascript/angular2:platform_browser",
        "//third_party/javascript/angular2:router",
        "//third_party/javascript/node_modules/rxjs",
    ],
)
