load("//javascript/angular2:build_defs.bzl", "ng_module")

package(default_visibility = ["//experimental/users/jasonlewis/scaffolding/angular/example-routing-basic:internal"])

ng_module(
    name = "baz",
    srcs = ["baz.ts"],
    deps = ["//third_party/javascript/angular2:core"],
)
